# Generated by Django 5.0.6 on 2024-10-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuimage',
            name='image',
            field=models.ImageField(null=True, upload_to='menu_images/'),
        ),
    ]
