# Generated by Django 5.0.6 on 2024-10-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_menuimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuimage',
            name='description',
            field=models.TextField(default='no description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuimage',
            name='image',
            field=models.ImageField(default='nessuna descrizione', upload_to='menu_images/'),
            preserve_default=False,
        ),
    ]
