# Generated by Django 5.0.6 on 2024-10-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_menuimage_description_alter_menuimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuimage',
            name='description',
            field=models.CharField(default='Immagine del Menù', max_length=255),
        ),
    ]
