# Generated by Django 5.0.6 on 2024-12-09 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_prenotazione'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prenotazione',
        ),
    ]
