# Generated by Django 5.0.6 on 2024-11-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='hashtag',
            field=models.CharField(blank=True, help_text='Inserisci massimo 3 hashtag separati da virgola.', max_length=255),
        ),
    ]
