# Generated by Django 5.0.6 on 2024-11-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0003_alter_customer_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='hashtag',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
