# Generated by Django 5.0.6 on 2024-11-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0004_alter_customer_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_time',
            field=models.CharField(max_length=5),
        ),
    ]
