# Generated by Django 5.0.6 on 2024-12-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0006_disableddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_time',
            field=models.CharField(max_length=10),
        ),
    ]
