# Generated by Django 5.0.6 on 2024-12-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0007_alter_reservation_reservation_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisabledTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('date', 'start_time', 'end_time')},
            },
        ),
    ]
