# Generated by Django 5.0.6 on 2024-12-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0009_rename_date_disabledtimeslot_end_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisabledTimeSlot',
        ),
        migrations.AddField(
            model_name='disableddate',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disableddate',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disableddate',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='disableddate',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
