# Generated by Django 5.0.6 on 2024-12-06 22:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0010_delete_disabledtimeslot_disableddate_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disableddate',
            name='date',
            field=models.DateField(help_text='Date to disable for reservations'),
        ),
        migrations.AlterField(
            model_name='disableddate',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Ora di fine disabilitata (opzionale)', null=True),
        ),
        migrations.AlterField(
            model_name='disableddate',
            name='reason',
            field=models.TextField(blank=True, default=django.utils.timezone.now, help_text='Optional reason for disabling the date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disableddate',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Ora di inizio disabilitata (opzionale)', null=True),
        ),
    ]
