# Generated by Django 5.0.6 on 2024-12-07 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0013_remove_disableddate_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disableddate',
            name='date',
            field=models.DateField(help_text='Date to disable', unique=True),
        ),
        migrations.AlterField(
            model_name='disableddate',
            name='end_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='disableddate',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='disableddate',
            name='start_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
