# Generated by Django 5.0.6 on 2024-12-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0015_disabledtimeslot_remove_disableddate_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disabledtimeslot',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
