# Generated by Django 5.0.6 on 2024-12-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0017_alter_disabledtimeslot_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disabledtimeslot',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='disabledtimeslot',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='disabledtimeslot',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='disabledtimeslot',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='disabledtimeslot',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='disabledtimeslot',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
