# Generated by Django 5.0.6 on 2025-04-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0018_alter_disabledtimeslot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
