# Generated by Django 5.0.6 on 2025-12-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0019_reservation_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='restaurant_id',
            field=models.CharField(choices=[('SCARPETTA', 'La Scarpetta'), ('BRACERIA', 'La Braceria')], default='SCARPETTA', help_text='Identificativo del ristorante', max_length=20),
        ),
    ]
